In [33]:
import pandas as pd
import numpy as np

import tkinter as tk
from tkinter import filedialog

In [9]:
file3=r"E:\WORK\网格酬金核算\test\2022年3月服务中心酬金核算结果.xlsx"

In [20]:
df_tmp=pd.read_excel(file3,sheet_name='服务中心汇总',skiprows=0,header=[0,1,2])

In [ ]:
df_tmp.columns.values

In [29]:
#合并数据
def merge_excel(file,outpath):

    li=pd.DataFrame()
    for i in file:
        df_tmp=pd.read_excel(i,sheet_name='服务中心汇总',skiprows=0,header=[0,1,2])
        li=pd.concat([li,df_tmp])

    writer = pd.ExcelWriter(r'E:\WORK\网格酬金核算\test/'+outpath)
    li.to_excel(writer,'Sheet1')
     
    writer.save()
    writer.close()

In [ ]:
import pandas as pd
from sqlalchemy import false
file3=r"E:\WORK\网格酬金核算\test\2022年3月服务中心酬金核算结果.xlsx"
file4=r"E:\WORK\网格酬金核算\test\2022年4月服务中心酬金核算结果.xlsx"
file5=r"E:\WORK\网格酬金核算\test\2022年5月服务中心酬金核算结果.xlsx"
file6=r"E:\WORK\网格酬金核算\test\2022年6月服务中心酬金核算结果.xlsx"
file7=r"E:\WORK\网格酬金核算\test\2022年7月服务中心酬金核算结果.xlsx"
file8=r"E:\WORK\网格酬金核算\test\2022年8月服务中心酬金核算结果.xlsx"
file9=r"E:\WORK\网格酬金核算\test\2022年9月服务中心酬金核算结果.xlsx"
file=[file3,file4,file5,file6]

merge_excel(file,'3-6.xlsx')

file=[file7,file8]

merge_excel(file,'7-8.xlsx')

file=[file8,file9]

merge_excel(file,'8-9.xlsx')

In [34]:
print('正在打开……')
df_mr=pd.DataFrame()
root = tk.Tk()
root.withdraw()
# path = filedialog.askopenfilename()
# path_out, temp = os.path.split(path)
# file_name, extension = os.path.splitext(temp)
# print('path:', path_out)
# print('file_name:', file_name)
# print('extension:', extension)

path = filedialog.askopenfilename()

正在打开……

In [50]:
df=pd.read_excel(path,sheet_name=0,skiprows=2,parse_dates=['Unnamed: 0'],index_col='Unnamed: 0',dtype='float64')

In [51]:
df.index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            133, 134, 135, 136, 137, 138, 139, 140, 141, 142],
           dtype='int64', length=286)

In [52]:
df_res=df.pct_change(periods=143)

In [53]:
df_res

,目标值,完成值,完成率,类型得分,得分,"修正得分(无上限，规则：得分*5/6,超出类型得分，则得分*5/6+得分-类型得分)",去年12月份额,当月份额,改善度目标,改善度,...,排名.1,排名得分.1,规模系数.1,最终得分.1,服务中心人数.1,不含激励奖金.1,9月客户发展激励,9月宽带发展激励,8月客户发展激励补发,奖金.1
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,-0.034106,-0.003635,0.031547,0.0,0.031547,0.037761,0.0,-0.002276,0.0,0.121951,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,-0.034080,-0.005137,0.029964,0.0,0.029964,0.035434,0.0,-0.003429,0.0,0.146853,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,-0.034218,-0.000649,0.034758,0.0,0.034758,0.041457,0.0,-0.000816,0.0,0.051546,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,-0.034094,-0.004843,0.030283,0.0,0.030283,0.036218,0.0,-0.001448,0.0,0.085714,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,0.013388,-0.013151,-0.026188,0.0,-0.026188,-0.030674,0.0,-0.004404,0.0,-1.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
lindex=path.rfind('/')

In [55]:
out_path=path[0:lindex+1]+'环比结果.xlsx'

In [56]:
df_res.to_excel(out_path)