In [1]:
import pandas as pd
import numpy as np

import tkinter as tk
from tkinter import filedialog

In [14]:
print('正在打开……')
df_mr=pd.DataFrame()
root = tk.Tk()
root.withdraw()
# path = filedialog.askopenfilename()
# path_out, temp = os.path.split(path)
# file_name, extension = os.path.splitext(temp)
# print('path:', path_out)
# print('file_name:', file_name)
# print('extension:', extension)

path = filedialog.askopenfilename()

正在打开……

In [15]:
df=pd.read_excel(path,sheet_name='Sheet3',skiprows=2,parse_dates=['Unnamed: 0'],index_col='Unnamed: 0')

In [16]:
df

,Unnamed: 1,目标值,完成值,完成率,类型得分,得分,"修正得分(无上限，规则：得分*5/6,超出类型得分，则得分*5/6+得分-类型得分)",去年12月份额,当月份额,改善度,...,类型得分.13,得分.13,修正得分.10,完成值总分,排名,排名得分,规模系数,最终得分,服务中心人数,奖金
202203,1277402,313.520000,295.364529,0.942092,20,17.104575,14.253813,0.542132,0.540402,-0.001730,...,5,1.272656,1.060547,38.798027,19,64,1.10,64,4,6526.00
202203,1391551,299.570000,294.627550,0.983502,20,19.175076,15.979230,0.571055,0.568882,-0.002172,...,5,0.745312,0.621094,28.490773,21,60,1.10,60,3,4895.40
202203,1277400,493.750000,500.191239,1.013046,20,20.652277,17.318944,0.609730,0.611547,0.001816,...,5,1.378125,1.148438,71.667968,8,88,1.10,88,4,8239.30
202203,1589617,256.760000,315.345470,1.228172,20,31.408605,28.075272,0.581423,0.580041,-0.001381,...,5,1.202344,1.001953,51.331579,15,72,1.05,72,4,6926.64
202203,1277405,306.480000,315.521133,1.029500,20,21.474996,18.141662,0.601299,0.600677,-0.000622,...,5,0.143750,0.119792,78.015715,4,96,1.10,96,3,6656.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202204,1670397,346.191202,387.271652,1.118664,20,25.933203,22.599869,0.671400,0.666000,-0.005400,...,4,0.030227,0.025189,58.508282,17,76,1.10,76,1,2173.60
202204,1670401,259.876822,310.341282,1.194186,20,29.709304,26.375970,0.626700,0.621300,-0.005400,...,4,0.929293,0.774411,59.811082,13,84,1.05,84,1,2193.20
202204,1670398,179.947121,195.053688,1.083950,20,24.197502,20.864168,0.622500,0.615100,-0.007400,...,4,1.373737,1.144781,55.385523,20,72,1.05,72,1,1965.60
202204,1670399,508.967635,522.530624,1.026648,20,21.332402,17.999069,0.632100,0.626300,-0.005800,...,4,1.333333,1.111111,51.444398,22,68,1.15,68,1,2033.20
202204,1670441,331.486284,346.599273,1.045592,20,22.279580,18.946246,0.611300,0.611300,0.000000,...,4,3.080808,2.567340,73.217267,4,96,1.10,96,1,2745.60

In [17]:
df_res=df.pct_change(periods=143)

In [18]:
df_res

,Unnamed: 1,目标值,完成值,完成率,类型得分,得分,"修正得分(无上限，规则：得分*5/6,超出类型得分，则得分*5/6+得分-类型得分)",去年12月份额,当月份额,改善度,...,类型得分.13,得分.13,修正得分.10,完成值总分,排名,排名得分,规模系数,最终得分,服务中心人数,奖金
202203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202204,0.0,2.896356,3.414313,0.132934,0.0,0.338817,0.400078,0.015123,0.015121,0.015364,...,-0.2,-0.700361,-0.700361,0.349664,-0.227273,0.117647,0.0,0.117647,0.0,0.117647
202204,0.0,2.860895,3.346843,0.125864,0.0,0.289791,0.338823,-0.009985,-0.017191,5.329865,...,-0.2,17.424242,17.424242,0.108212,-0.235294,0.105263,0.0,0.105263,0.0,0.057066
202204,0.0,2.877335,3.032019,0.039894,0.0,0.094005,0.110686,0.016205,0.008294,1.921481,...,-0.2,0.210482,0.210482,-0.056383,1.000000,-0.181818,0.0,-0.181818,0.0,-0.181818
202204,0.0,2.889703,2.875106,-0.003753,0.0,-0.008983,-0.010628,-0.009946,-0.012788,0.436552,...,-0.2,-0.222506,-0.222506,-0.129167,1.444444,-0.260870,0.0,-0.260870,0.0,-0.260870
202204,0.0,2.922450,2.939414,0.004325,0.0,0.010208,0.012025,0.005271,0.009071,-1.000000,...,-0.2,-0.383838,-0.383838,0.259041,-0.666667,0.090909,0.0,0.090909,0.0,0.090909

In [19]:
lindex=path.rfind('/')

In [20]:
out_path=path[0:lindex+1]+'环比结果.xlsx'

In [21]:
df_res.to_excel(out_path)